#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#include <stdio.h>

#define LIGHT_URI_PATH "light"
#define TEMP_PUB_URI_PATH "temp_pub"
#define COAP_PORT 5683

#define OT_CONNECTION_LED DK_LED1

enum ot_thread_commands {
	THREAD_COAP_LIGHT_CMD_OFF = '0',
	THREAD_COAP_LIGHT_CMD_ON = '1',
	THREAD_COAP_LIGHT_CMD_TOGGLE = '2',
	THREAD_COAP_TEMP_PUBLISH_ON_CMD = '3',
	THREAD_COAP_TEMP_PUBLISH_OFF_CMD = '4'
};

#endif // DEFINITIONS_H
